channels:
- defaults
- conda-forge
dependencies:
- python=3.9.13
- pip<=24.0
- pip:
  - mlflow
  - asyncio==3.4.3
  - boto3==1.26.111
  - colorama==0.4.6
  - configparser==5.3.0
  - defusedxml==0.7.1
  - dill==0.3.6
  - fsspec==2023.4.0
  - google-cloud-vision==3.4.4
  - importlib-resources==5.12.0
  - jax==0.3.15
  - jaxlib
  - keras==2.9.0
  - lz4==4.3.2
  - pandas==1.5.3
  - pathlib==1.0.1
  - pillow==9.1.0
  - pydot==1.4.2
  - pyopenssl==23.1.1
  - tblib==1.7.0
  - tensorflow-macos==2.9.0
  - tensorflow
name: mlflow-env